// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { safeLocalStorage } from '@/lib/safeStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL?.trim();
// Support both current and legacy key names to prevent runtime crashes on older deploy envs.
const SUPABASE_PUBLISHABLE_KEY = (
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY?.trim()
  || import.meta.env.VITE_SUPABASE_ANON_KEY?.trim()
);

export const FALLBACK_SUPABASE_URL = 'https://invalid.supabase.co';
export const FALLBACK_SUPABASE_KEY = 'public-anon-key-missing';

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error(
    '[supabase] Missing environment variables. Expected VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY (or VITE_SUPABASE_ANON_KEY).',
  );
}

/** False when env was missing at build time — requests hit a dead host and look like a "network" error. */
export function isSupabaseBrowserClientConfigured(): boolean {
  const url = import.meta.env.VITE_SUPABASE_URL?.trim();
  const key = (
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY?.trim()
    || import.meta.env.VITE_SUPABASE_ANON_KEY?.trim()
  );
  if (!url || !key) return false;
  if (url === FALLBACK_SUPABASE_URL || url.includes('invalid.supabase.co')) return false;
  if (key === FALLBACK_SUPABASE_KEY) return false;
  return true;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || FALLBACK_SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY || FALLBACK_SUPABASE_KEY,
  {
    auth: {
      storage: safeLocalStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true, // Ensure magic link tokens are processed
    },
  },
);
