// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { safeLocalStorage } from '@/lib/safeStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL?.trim();
// Support both current and legacy key names to prevent runtime crashes on older deploy envs.
const SUPABASE_PUBLISHABLE_KEY = (
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY?.trim()
  || import.meta.env.VITE_SUPABASE_ANON_KEY?.trim()
);

export const FALLBACK_SUPABASE_URL = 'https://invalid.supabase.co';
export const FALLBACK_SUPABASE_KEY = 'public-anon-key-missing';

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error(
    '[supabase] Missing environment variables. Expected VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY (or VITE_SUPABASE_ANON_KEY).',
  );
}

/** Why the baked Supabase client is not usable (Vite inlines `import.meta.env` at build time). */
export type SupabaseBrowserConfigIssue =
  | 'missing_url'
  | 'missing_key'
  | 'both_missing'
  | 'placeholder_url'
  | 'placeholder_key';

function isTruthyEnv(value: string | undefined): boolean {
  if (value == null) return false;
  const t = value.trim();
  if (!t) return false;
  const lower = t.toLowerCase();
  return lower !== 'undefined' && lower !== 'null' && lower !== '0';
}

function looksLikePlaceholderUrl(url: string): boolean {
  const u = url.trim().toLowerCase();
  return (
    u === FALLBACK_SUPABASE_URL
    || u.includes('invalid.supabase.co')
    || u.includes('your-project.supabase.co')
    || u.includes('placeholder')
  );
}

function looksLikePlaceholderKey(key: string): boolean {
  const k = key.trim().toLowerCase();
  return (
    k === FALLBACK_SUPABASE_KEY.toLowerCase()
    || k.includes('your-publishable')
    || k.includes('your-anon')
    || k.includes('replace_me')
    || k.includes('changeme')
    || k.includes('example')
  );
}

/** Use for targeted user messaging; `null` means URL + key look present and non-placeholder. */
export function getSupabaseBrowserConfigIssue(): SupabaseBrowserConfigIssue | null {
  const urlRaw = import.meta.env.VITE_SUPABASE_URL;
  const keyRaw =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? import.meta.env.VITE_SUPABASE_ANON_KEY;

  const url = typeof urlRaw === 'string' ? urlRaw.trim() : '';
  const key = typeof keyRaw === 'string' ? keyRaw.trim() : '';

  const hasUrl = isTruthyEnv(url);
  const hasKey = isTruthyEnv(key);

  if (!hasUrl && !hasKey) return 'both_missing';
  if (!hasUrl) return 'missing_url';
  if (!hasKey) return 'missing_key';

  if (looksLikePlaceholderUrl(url)) return 'placeholder_url';
  if (looksLikePlaceholderKey(key)) return 'placeholder_key';

  return null;
}

/** False when env was missing at build time — requests hit a dead host and look like a "network" error. */
export function isSupabaseBrowserClientConfigured(): boolean {
  return getSupabaseBrowserConfigIssue() === null;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || FALLBACK_SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY || FALLBACK_SUPABASE_KEY,
  {
    auth: {
      storage: safeLocalStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true, // Ensure magic link tokens are processed
    },
  },
);
